![Los Angeles skyline](la_skyline.jpg)

Los Angeles, California ðŸ˜Ž. The City of Angels. Tinseltown. The Entertainment Capital of the World! 

Known for its warm weather, palm trees, sprawling coastline, and Hollywood, along with producing some of the most iconic films and songs. However, as with any highly populated city, it isn't always glamorous and there can be a large volume of crime. That's where you can help!

You have been asked to support the Los Angeles Police Department (LAPD) by analyzing crime data to identify patterns in criminal behavior. They plan to use your insights to allocate resources effectively to tackle various crimes in different areas.

## The Data

They have provided you with a single dataset to use. A summary and preview are provided below.

It is a modified version of the original data, which is publicly available from Los Angeles Open Data.

# crimes.csv

| Column     | Description              |
|------------|--------------------------|
| `'DR_NO'` | Division of Records Number: Official file number made up of a 2-digit year, area ID, and 5 digits. |
| `'Date Rptd'` | Date reported - MM/DD/YYYY. |
| `'DATE OCC'` | Date of occurrence - MM/DD/YYYY. |
| `'TIME OCC'` | In 24-hour military time. |
| `'AREA NAME'` | The 21 Geographic Areas or Patrol Divisions are also given a name designation that references a landmark or the surrounding community that it is responsible for. For example, the 77th Street Division is located at the intersection of South Broadway and 77th Street, serving neighborhoods in South Los Angeles. |
| `'Crm Cd Desc'` | Indicates the crime committed. |
| `'Vict Age'` | Victim's age in years. |
| `'Vict Sex'` | Victim's sex: `F`: Female, `M`: Male, `X`: Unknown. |
| `'Vict Descent'` | Victim's descent:<ul><li>`A` - Other Asian</li><li>`B` - Black</li><li>`C` - Chinese</li><li>`D` - Cambodian</li><li>`F` - Filipino</li><li>`G` - Guamanian</li><li>`H` - Hispanic/Latin/Mexican</li><li>`I` - American Indian/Alaskan Native</li><li>`J` - Japanese</li><li>`K` - Korean</li><li>`L` - Laotian</li><li>`O` - Other</li><li>`P` - Pacific Islander</li><li>`S` - Samoan</li><li>`U` - Hawaiian</li><li>`V` - Vietnamese</li><li>`W` - White</li><li>`X` - Unknown</li><li>`Z` - Asian Indian</li> |
| `'Weapon Desc'` | Description of the weapon used (if applicable). |
| `'Status Desc'` | Crime status. |
| `'LOCATION'` | Street address of the crime. |

In [1]:
# Re-run this cell
#Â Import required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
crimes = pd.read_csv("crimes.csv", parse_dates=["Date Rptd", "DATE OCC"], dtype={"TIME OCC": str})
crimes.head()

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA NAME,Crm Cd Desc,Vict Age,Vict Sex,Vict Descent,Weapon Desc,Status Desc,LOCATION
0,220314085,2022-07-22,2020-05-12,1110,Southwest,THEFT OF IDENTITY,27,F,B,NaN,Invest Cont,2500 S SYCAMORE AV
1,222013040,2022-08-06,2020-06-04,1620,Olympic,THEFT OF IDENTITY,60,M,H,NaN,Invest Cont,3300 SAN MARINO ST
2,220614831,2022-08-18,2020-08-17,1200,Hollywood,THEFT OF IDENTITY,28,M,H,NaN,Invest Cont,1900 TRANSIENT
3,231207725,2023-02-27,2020-01-27,0635,77th Street,THEFT OF IDENTITY,37,M,H,NaN,Invest Cont,6200 4TH AV
4,220213256,2022-07-14,2020-07-14,0900,Rampart,THEFT OF IDENTITY,79,M,B,NaN,Invest Cont,1200 W 7TH ST

In [2]:
# Start coding here
# Use as many cells as you need
crimes.dtypes

DR_NO                    int64
Date Rptd       datetime64[ns]
DATE OCC        datetime64[ns]
TIME OCC                object
AREA NAME               object
Crm Cd Desc             object
Vict Age                 int64
Vict Sex                object
Vict Descent            object
Weapon Desc             object
Status Desc             object
LOCATION                object
dtype: object

Which hour has the highest frequency of crimes? Store as an integer variable called peak_crime_hour.

In [3]:
count_of_ea = crimes['TIME OCC'].value_counts()
count_of_ea.head()
peak_crime_hour = count_of_ea.idxmax()
peak_crime_hour

'1200'

Which area has the largest frequency of night crimes (crimes committed between 10pm and 3:59am)? Save as a string variable called peak_night_crime_location.

Time on The dataframe is in 24h format, and is not human friendly cuz it does not have the ":" separating hours and mins.
Lets fix it

In [4]:
# Function to convert TIME OCC column to datetime.time
from datetime import datetime, time

def convert_time_occ_column(crimes):
    crimes['TIME OCC'] = crimes['TIME OCC'].apply(lambda x: datetime.strptime(f'{x:04}', '%H%M').time())
    print(f"Column 'TIME OCC' converted to type: {crimes['TIME OCC'].dtype}")

# Convert TIME OCC column
convert_time_occ_column(crimes)

Column 'TIME OCC' converted to type: object

In [5]:
# Define the nighttime range
night_start = time(22, 0)  # 10:00 PM
night_end = time(3, 59)    # 3:59 AM

# Function to filter nighttime crimes
def is_nighttime(crime_time):
    return (crime_time >= night_start) or (crime_time <= night_end)

# Filter for nighttime crimes
nighttime_crimes = crimes[crimes['TIME OCC'].apply(is_nighttime)]

print("\nFiltered DataFrame with nighttime crimes:")
nighttime_crimes.head()

Filtered DataFrame with nighttime crimes:

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA NAME,Crm Cd Desc,Vict Age,Vict Sex,Vict Descent,Weapon Desc,Status Desc,LOCATION
8,231207476,2023-02-27,2020-08-15,00:01:00,77th Street,BURGLARY,72,M,B,NaN,Invest Cont,8800 HAAS AV
10,221711184,2022-06-15,2020-05-15,01:55:00,Devonshire,THEFT OF IDENTITY,27,M,B,NaN,Invest Cont,8300 WHITE OAK AV
30,221314362,2022-07-11,2020-04-07,00:01:00,Newton,THEFT OF IDENTITY,53,F,H,NaN,Invest Cont,1600 E OLYMPIC BL
33,231307252,2023-03-03,2020-07-05,23:05:00,Newton,THEFT OF IDENTITY,22,F,B,NaN,Invest Cont,6600 S BROADWAY
36,221614254,2022-11-13,2020-01-01,00:01:00,Foothill,THEFT OF IDENTITY,22,F,H,NaN,Invest Cont,10200 TELFAIR AV

## Which area has the largest frequency of night crimes

In [6]:
# Find the area with the largest frequency of nighttime crimes
most_frequent_area = nighttime_crimes['AREA NAME'].value_counts().idxmax()
frequency = nighttime_crimes['AREA NAME'].value_counts().max()

print(f"The area with the largest frequency of nighttime crimes is: {most_frequent_area} with {frequency} crimes")

The area with the largest frequency of nighttime crimes is: Central with 3312 crimes

In [7]:
peak_night_crime_location = "Central"

In [8]:
# Define age group bins
bins = [0, 18, 26, 35, 45, 55, 65, float('inf')]
labels = ["0-17", "18-25", "26-34", "35-44", "45-54", "55-64", "65+"]

# Categorize ages into bins and count occurrences
crimes['Age Group'] = pd.cut(crimes['Vict Age'], bins=bins, labels=labels, right=False)

# Count occurrences of each age group
age_group_counts = crimes['Age Group'].value_counts()

# Sort index to ensure age groups are in order
age_group_counts = age_group_counts.reindex(labels)

# Create pandas Series with age group labels as index and counts as values
victim_ages = pd.Series(age_group_counts, index=labels)

# Display the resulting Series
print(victim_ages)

0-17      4528
18-25    28291
26-34    47470
35-44    42157
45-54    28353
55-64    20169
65+      14747
Name: count, dtype: int64